servers=[
  {
    :id => 2,
    :hostname => "agent",
    :sshport => "600",
    :address => "192.168.121."
  },
  {
    :id => 3,
    :hostname => "manager",
    :sshport => "600",
    :address => "192.168.121."
  }
]

result = []

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node| 
      config.vm.provider :libvirt do |lv|
        lv.memory = 128
        lv.cpus = 1
      end
      node.vm.network :private_network, :ip => machine[:address] + machine[:id].to_s
    end
    result.push({
      :IP => machine[:address] + machine[:id].to_s,
      :hostname => "vagrant_" + machine[:hostname]      
      })
  end

  File.open('vagrant_result.json', 'w') { |file| file.write(result) }

end
