
servers=[
  {
    :hostname => "agent",
    :provision => "playbook.yml"
  },
  {
    :hostname => "manager",
    :provision => "playbook.yml"
  }
]

Vagrant.configure('2') do |config|
  config.ssh.password = 'root'
  config.ssh.username = 'root'
  
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = 'centos/7'
      node.memory = '256m'
    end
  end

#  config.vm.provider 'docker' do |d|
#    d.build_dir = './'
#    d.name = 'Wazuh'
#    d.expose = [22]
#    d.ports = ['2222:22']
#    d.has_ssh = true
#    d.cmd = ['tail', '-f', '/dev/null']
#    d.cmd = ['/usr/sbin/sshd', '-D']
#  end

#  config.vm.provision 'ansible' do |ansible|
#    ansible.playbook      = 'playbook.yml'
#    ansible.host_key_checking = false
#    ansible.become          = true
#    ansible.verbose = 'vv'
#  end
end


