servers=[
  {
    :id => 2,
    :hostname => "Agent",
    :sshport => "600",
    :address => "192.168.121."
  },
  {
    :id => 3,
    :hostname => "Manager",
    :sshport => "600",
    :address => "192.168.121."
  }
]

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  servers.each do |server|
    config.vm.define server[:hostname] do |node| 
      config.vm.provider :libvirt do |lv|
        lv.memory = 128
        lv.cpus = 1
      end
      node.vm.network :private_network, :ip => server[:address] + server[:id].to_s
    end
  end

  #config.vm.define :agent do |agent|
  #  agent.vm.network :public_network,
  #    :dev => ""
  #end
end
