---
- hosts: managerInstance
  roles:
    - ansible-wazuh-manager
  vars:
    wazuh_managers:
      - address: "{{ hostvars[groups.Managers[0]]['ansible_host'] }}"
        port: 1514
        protocol: udp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
    wazuh_agent_authd:
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: 'no'
