---
- hosts: vagrant_Agent
  vars:
    manager_IP: "{{ hostvars['vagrant_Manager']['ansible_host'] }}"

  tasks:
  - name: Echo Server, Agent => Manager
    command: ping -c 4 {{ manager_IP }}
    
