---
- hosts: vagrant_Manager
  vars:
    agent_IP: "{{ hostvars['vagrant_Agent']['ansible_host'] }}"

  tasks:
  - name: Echo Server, Manager => Agent
    command: ping -c 4 {{ agent_IP }}
    
